nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000'] 
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/': 
            allow_origin: ['http://localhost:3000']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
